In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('heart_disease_dataset.csv')

In [ ]:
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75  Female          228             119          66  Current   
1     48    Male          204             165          62  Current   
2     53    Male          234              91          67    Never   
3     69  Female          192              90          72  Current   
4     62  Female          172             163          93    Never   
..   ...     ...          ...             ...         ...      ...   
995   56  Female          269             111          86    Never   
996   78  Female          334             145          76    Never   
997   79    Male          151             179          81    Never   
998   60  Female          326             151          68   Former   
999   53    Male          226             116          82  Current   

    Alcohol Intake  Exercise Hours Family History Diabetes Obesity  \
0            Heavy               1             No       No     Yes   
1              NaN               5             No       No      No   
2            Heavy               3            Yes       No     Yes   
3              NaN               4             No      Yes      No   
4              NaN               6             No      Yes      No   
..             ...             ...            ...      ...     ...   
995          Heavy               5             No      Yes     Yes   
996            NaN               6             No       No      No   
997       Moderate               4            Yes       No     Yes   
998            NaN               8            Yes      Yes      No   
999            NaN               6             No       No     Yes   

     Stress Level  Blood Sugar Exercise Induced Angina   Chest Pain Type  \
0               8          119                     Yes   Atypical Angina   
1               9           70                     Yes    Typical Angina   
2               5          196                     Yes   Atypical Angina   
3               7          107                     Yes  Non-anginal Pain   
4               2          183                     Yes      Asymptomatic   
..            ...          ...                     ...               ...   
995            10          120                      No  Non-anginal Pain   
996            10          196                     Yes    Typical Angina   
997             8          189                     Yes      Asymptomatic   
998             5          174                     Yes   Atypical Angina   
999             5          161                     Yes      Asymptomatic   

     Heart Disease  
0                1  
1                0  
2                1  
3                0  
4                0  
..             ...  
995              1  
996              1  
997              0  
998              1  
999              1  

[1000 rows x 16 columns]

In [ ]:
df.isnull().sum()

Age                          0
Gender                       0
Cholesterol                  0
Blood Pressure               0
Heart Rate                   0
Smoking                      0
Alcohol Intake             340
Exercise Hours               0
Family History               0
Diabetes                     0
Obesity                      0
Stress Level                 0
Blood Sugar                  0
Exercise Induced Angina      0
Chest Pain Type              0
Heart Disease                0
dtype: int64

In [ ]:
df.dropna(inplace= True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Smoking'] = le.fit_transform(df['Smoking'])
df['Alcohol Intake'] = le.fit_transform(df['Alcohol Intake'])
df['Chest Pain Type'] = le.fit_transform(df['Chest Pain Type'])
df['Obesity'] = le.fit_transform(df['Obesity'])
df['Family History'] = le.fit_transform(df['Family History'])
df['Heart Disease'] = le.fit_transform(df['Heart Disease'])
df['Exercise Induced Angina'] = le.fit_transform(df['Exercise Induced Angina'])
df['Diabetes'] = le.fit_transform(df['Diabetes'])
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75       0          228             119          66        0   
2     53       1          234              91          67        2   
6     64       0          211             105          86        1   
7     60       0          208             148          83        2   
8     37       0          317             137          66        0   
..   ...     ...          ...             ...         ...      ...   
991   26       0          215             100          74        2   
992   28       0          220             102          73        0   
994   52       1          248             159          76        1   
995   56       0          269             111          86        2   
997   79       1          151             179          81        2   

     Alcohol Intake  Exercise Hours  Family History  Diabetes  Obesity  \
0                 0               1               0         0        1   
2                 0               3               1         0        1   
6                 0               8               1         1        1   
7                 1               4               0         1        1   
8                 0               3               0         1        1   
..              ...             ...             ...       ...      ...   
991               0               7               0         1        0   
992               1               7               1         1        1   
994               1               9               0         1        1   
995               0               5               0         1        1   
997               1               4               1         0        1   

     Stress Level  Blood Sugar  Exercise Induced Angina  Chest Pain Type  \
0               8          119                        1                1   
2               5          196                        1                1   
6               2          120                        0                3   
7               2          113                        1                0   
8               5          114                        0                2   
..            ...          ...                      ...              ...   
991            10          135                        0                1   
992            10          102                        0                3   
994             2          152                        1                0   
995            10          120                        0                2   
997             8          189                        1                0   

     Heart Disease  
0                1  
2                1  
6                1  
7                1  
8                0  
..             ...  
991              0  
992              0  
994              1  
995              1  
997              0  

[660 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 660 entries, 0 to 997
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      660 non-null    int64
 1   Gender                   660 non-null    int64
 2   Cholesterol              660 non-null    int64
 3   Blood Pressure           660 non-null    int64
 4   Heart Rate               660 non-null    int64
 5   Smoking                  660 non-null    int64
 6   Alcohol Intake           660 non-null    int64
 7   Exercise Hours           660 non-null    int64
 8   Family History           660 non-null    int64
 9   Diabetes                 660 non-null    int64
 10  Obesity                  660 non-null    int64
 11  Stress Level             660 non-null    int64
 12  Blood Sugar              660 non-null    int64
 13  Exercise Induced Angina  660 non-null    int64
 14  Chest Pain Type          660 non-null    int64
 15  Heart Disea

In [ ]:
df.corr()

Age    Gender  Cholesterol  Blood Pressure  \
Age                      1.000000  0.004848     0.007875        0.004500   
Gender                   0.004848  1.000000    -0.025584       -0.075573   
Cholesterol              0.007875 -0.025584     1.000000        0.027309   
Blood Pressure           0.004500 -0.075573     0.027309        1.000000   
Heart Rate               0.050212  0.022431    -0.010819       -0.006665   
Smoking                 -0.042466 -0.018998     0.012810        0.015343   
Alcohol Intake           0.093875 -0.012976     0.053458       -0.011483   
Exercise Hours          -0.007590 -0.039730     0.008885       -0.011361   
Family History           0.010722  0.094037    -0.036683       -0.000513   
Diabetes                -0.031614 -0.051294    -0.068161       -0.065743   
Obesity                  0.002003 -0.075548     0.015841       -0.043429   
Stress Level            -0.086295  0.034863     0.115721        0.018005   
Blood Sugar             -0.040666  0.053840    -0.004058       -0.092608   
Exercise Induced Angina -0.019522  0.013292     0.035075        0.024771   
Chest Pain Type         -0.024976 -0.001107    -0.106206        0.006195   
Heart Disease            0.648068  0.031281     0.369807        0.021624   

                         Heart Rate   Smoking  Alcohol Intake  Exercise Hours  \
Age                        0.050212 -0.042466        0.093875       -0.007590   
Gender                     0.022431 -0.018998       -0.012976       -0.039730   
Cholesterol               -0.010819  0.012810        0.053458        0.008885   
Blood Pressure            -0.006665  0.015343       -0.011483       -0.011361   
Heart Rate                 1.000000 -0.039496        0.002137       -0.006712   
Smoking                   -0.039496  1.000000        0.004237       -0.014182   
Alcohol Intake             0.002137  0.004237        1.000000        0.005267   
Exercise Hours            -0.006712 -0.014182        0.005267        1.000000   
Family History             0.060931 -0.011084       -0.036406        0.081056   
Diabetes                   0.028336  0.055490       -0.000294       -0.003190   
Obesity                   -0.030638 -0.033948        0.036228       -0.006643   
Stress Level              -0.030095  0.021193        0.002336        0.019318   
Blood Sugar                0.023769 -0.040360        0.008206       -0.010864   
Exercise Induced Angina    0.037545  0.008432        0.001662        0.068374   
Chest Pain Type            0.003958 -0.027963        0.024101        0.040182   
Heart Disease              0.040874 -0.012769        0.076589       -0.005986   

                         Family History  Diabetes   Obesity  Stress Level  \
Age                            0.010722 -0.031614  0.002003     -0.086295   
Gender                         0.094037 -0.051294 -0.075548      0.034863   
Cholesterol                   -0.036683 -0.068161  0.015841      0.115721   
Blood Pressure                -0.000513 -0.065743 -0.043429      0.018005   
Heart Rate                     0.060931  0.028336 -0.030638     -0.030095   
Smoking                       -0.011084  0.055490 -0.033948      0.021193   
Alcohol Intake                -0.036406 -0.000294  0.036228      0.002336   
Exercise Hours                 0.081056 -0.003190 -0.006643      0.019318   
Family History                 1.000000  0.018182  0.021247      0.060672   
Diabetes                       0.018182  1.000000 -0.014827     -0.074409   
Obesity                        0.021247 -0.014827  1.000000      0.029056   
Stress Level                   0.060672 -0.074409  0.029056      1.000000   
Blood Sugar                   -0.060053 -0.010502 -0.041366      0.002514   
Exercise Induced Angina       -0.006086 -0.055327  0.014409     -0.009019   
Chest Pain Type                0.008112  0.054046  0.047708     -0.000518   
Heart Disease                 -0.006194  0.017305  0.002839     -0.032253   

                         Blood Sugar  Exercise In

In [ ]:
df.drop('Exercise Hours', axis = 1, inplace = True)
df.drop('Obesity', axis = 1, inplace = True)
df.drop('Blood Sugar', axis = 1, inplace = True)
df.drop('Smoking', axis= 1, inplace = True)
df.drop('Chest Pain Type', axis= 1, inplace = True)
df.drop('Family History', axis = 1, inplace = True)
df.drop('Stress Level', axis = 1, inplace = True)

In [ ]:
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Alcohol Intake  \
0     75       0          228             119          66               0   
2     53       1          234              91          67               0   
6     64       0          211             105          86               0   
7     60       0          208             148          83               1   
8     37       0          317             137          66               0   
..   ...     ...          ...             ...         ...             ...   
991   26       0          215             100          74               0   
992   28       0          220             102          73               1   
994   52       1          248             159          76               1   
995   56       0          269             111          86               0   
997   79       1          151             179          81               1   

     Diabetes  Exercise Induced Angina  Heart Disease  
0           0                        1              1  
2           0                        1              1  
6           1                        0              1  
7           1                        1              1  
8           1                        0              0  
..        ...                      ...            ...  
991         1                        0              0  
992         1                        0              0  
994         1                        1              1  
995         1                        0              1  
997         0                        1              0  

[660 rows x 9 columns]

In [ ]:
df.corr()

Age    Gender  Cholesterol  Blood Pressure  \
Age                      1.000000  0.004848     0.007875        0.004500   
Gender                   0.004848  1.000000    -0.025584       -0.075573   
Cholesterol              0.007875 -0.025584     1.000000        0.027309   
Blood Pressure           0.004500 -0.075573     0.027309        1.000000   
Heart Rate               0.050212  0.022431    -0.010819       -0.006665   
Alcohol Intake           0.093875 -0.012976     0.053458       -0.011483   
Diabetes                -0.031614 -0.051294    -0.068161       -0.065743   
Exercise Induced Angina -0.019522  0.013292     0.035075        0.024771   
Heart Disease            0.648068  0.031281     0.369807        0.021624   

                         Heart Rate  Alcohol Intake  Diabetes  \
Age                        0.050212        0.093875 -0.031614   
Gender                     0.022431       -0.012976 -0.051294   
Cholesterol               -0.010819        0.053458 -0.068161   
Blood Pressure            -0.006665       -0.011483 -0.065743   
Heart Rate                 1.000000        0.002137  0.028336   
Alcohol Intake             0.002137        1.000000 -0.000294   
Diabetes                   0.028336       -0.000294  1.000000   
Exercise Induced Angina    0.037545        0.001662 -0.055327   
Heart Disease              0.040874        0.076589  0.017305   

                         Exercise Induced Angina  Heart Disease  
Age                                    -0.019522       0.648068  
Gender                                  0.013292       0.031281  
Cholesterol                             0.035075       0.369807  
Blood Pressure                          0.024771       0.021624  
Heart Rate                              0.037545       0.040874  
Alcohol Intake                          0.001662       0.076589  
Diabetes                               -0.055327       0.017305  
Exercise Induced Angina                 1.000000       0.005654  
Heart Disease                           0.005654       1.000000

In [ ]:
X = df.iloc[:,:-1].values
X

array([[ 75,   0, 228, ...,   0,   0,   1],
       [ 53,   1, 234, ...,   0,   0,   1],
       [ 64,   0, 211, ...,   0,   1,   0],
       ...,
       [ 52,   1, 248, ...,   1,   1,   1],
       [ 56,   0, 269, ...,   0,   1,   0],
       [ 79,   1, 151, ...,   1,   0,   1]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
#spiltting

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y , test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.04759104,  0.96647087,  1.20049844, ..., -0.94830405,
        -1.00379508, -0.89901011],
       [ 0.20751626,  0.96647087,  0.4292294 , ...,  1.05451411,
        -1.00379508, -0.89901011],
       [ 0.27129309, -1.03469234, -0.34203964, ..., -0.94830405,
         0.99621927, -0.89901011],
       ...,
       [ 0.90906134, -1.03469234, -0.08494996, ...,  1.05451411,
         0.99621927, -0.89901011],
       [-0.49402882, -1.03469234, -1.57607011, ..., -0.94830405,
         0.99621927, -0.89901011],
       [-0.55780565, -1.03469234,  0.82343357, ..., -0.94830405,
        -1.00379508,  1.11233454]])

In [ ]:
X_test

array([[-1.38690438, -1.03469234, -0.39345758, ...,  1.05451411,
         0.99621927, -0.89901011],
       [-0.87668977, -1.03469234, -0.83907969, ...,  1.05451411,
         0.99621927, -0.89901011],
       [ 1.35549912, -1.03469234,  0.84057289, ..., -0.94830405,
         0.99621927,  1.11233454],
       ...,
       [-0.23892152,  0.96647087,  1.32047362, ..., -0.94830405,
         0.99621927, -0.89901011],
       [-1.38690438,  0.96647087,  1.61184193, ...,  1.05451411,
        -1.00379508,  1.11233454],
       [ 0.78150769, -1.03469234, -1.33611974, ...,  1.05451411,
         0.99621927, -0.89901011]])

# **LOGISTIC**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]]


In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[78  5]
 [ 9 40]]


0.8939393939393939

# **KNN**

In [ ]:
X = df.iloc[:,:-1].values
X

array([[ 75,   0, 228, ...,   0,   0,   1],
       [ 53,   1, 234, ...,   0,   0,   1],
       [ 64,   0, 211, ...,   0,   1,   0],
       ...,
       [ 52,   1, 248, ...,   1,   1,   1],
       [ 56,   0, 269, ...,   0,   1,   0],
       [ 79,   1, 151, ...,   1,   0,   1]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
#spiltting

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y , test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.04759104,  0.96647087,  1.20049844, ..., -0.94830405,
        -1.00379508, -0.89901011],
       [ 0.20751626,  0.96647087,  0.4292294 , ...,  1.05451411,
        -1.00379508, -0.89901011],
       [ 0.27129309, -1.03469234, -0.34203964, ..., -0.94830405,
         0.99621927, -0.89901011],
       ...,
       [ 0.90906134, -1.03469234, -0.08494996, ...,  1.05451411,
         0.99621927, -0.89901011],
       [-0.49402882, -1.03469234, -1.57607011, ..., -0.94830405,
         0.99621927, -0.89901011],
       [-0.55780565, -1.03469234,  0.82343357, ..., -0.94830405,
        -1.00379508,  1.11233454]])

In [ ]:
X_test

array([[-1.38690438, -1.03469234, -0.39345758, ...,  1.05451411,
         0.99621927, -0.89901011],
       [-0.87668977, -1.03469234, -0.83907969, ...,  1.05451411,
         0.99621927, -0.89901011],
       [ 1.35549912, -1.03469234,  0.84057289, ..., -0.94830405,
         0.99621927,  1.11233454],
       ...,
       [-0.23892152,  0.96647087,  1.32047362, ..., -0.94830405,
         0.99621927, -0.89901011],
       [-1.38690438,  0.96647087,  1.61184193, ...,  1.05451411,
        -1.00379508,  1.11233454],
       [ 0.78150769, -1.03469234, -1.33611974, ...,  1.05451411,
         0.99621927, -0.89901011]])

In [ ]:
# model training

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 11, metric = 'minkowski')
classifier.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=11)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]]


In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[76  7]
 [ 6 43]]


0.9015151515151515

# **SUPPORT VECTOR MACHINE**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel ='linear', random_state= 0)
classifier.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]]


In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[76  7]
 [ 9 40]]


0.8787878787878788

# **NAIVE BAYES**

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB()

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[81  2]
 [ 7 42]]


0.9318181818181818

# **DECISION TREE**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[83  0]
 [ 0 49]]


1.0

# **RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[83  0]
 [ 0 49]]


1.0

In [ ]:
dict= {
    'Algo name': 'accuracy_score',
    'Logistic': 0.8939393939393939,
    'KNN': 0.9015151515151515,
    'SVM': 0.8787878787878788,
    'NAIVE BAYES': 0.9318181818181818,
    'DECISION TREE': 1.0,
    'RANDOM FOREST': 1.0
}

ser = pd.Series(dict)
print(ser)

Algo name        accuracy_score
Logistic               0.893939
KNN                    0.901515
SVM                    0.878788
NAIVE BAYES            0.931818
DECISION TREE               1.0
RANDOM FOREST               1.0
dtype: object


In [ ]:
data = np.array([0.893939,0.901515 , 0.878788, 0.931818 ,1.0, 1.0 ])

# providing an index
ser = pd.Series(data, index=['Logistic Regression', 'KNN', 'SVM', 'NAIVE_BAYES', 'DECSION_TREE', 'RANDOM_FOREST'])

print(ser)

Logistic Regression    0.893939
KNN                    0.901515
SVM                    0.878788
NAIVE_BAYES            0.931818
DECSION_TREE           1.000000
RANDOM_FOREST          1.000000
dtype: float64
